server:
  port: 8080

#spring:
#  redis:
#    host: 192.168.3.3
#    port: 6379
#    database: 3
#    redisson:
#      config: |
#        singleServerConfig:
#          address: redis://${spring.redis.host}:${spring.redis.port}
#          database: ${spring.redis.database}
spring:
  redis:
    host: 192.168.3.3
    port: 6379
    database: 3

